bind p = play_toggle()
bind q = quit()
# Time units are in ms
bind , = seek_snap(-1000)
bind . = seek_snap(1000)
bind < = seek_snap(-5000)
bind > = seek_snap(5000)
# You can call multiple fns in sequence
# FIXME: we need play() and pause()
bind [ = seek_snap(-5000) ; play_toggle() # Seek 5 seconds in the past and pause
bind ] = seek_snap(5000) ; play_toggle() # Seek 5 seconds in the future and pause

# Audio backend to use:
# values: pulseaudio, pipewire, none (auto)
# default: (auto)
audio_backend = "pipewire"

# Show milliseconds in timecodes
ui_timecode_ms = true

# So each line has form
# 1. bind {key} = fn(arg1, arg2, ...)
# 2. {opt} = {expr}
