bind 1 = play()
bind 2 = pause()
# TODO: implement stop() fn
bind p = play_toggle()
bind q = quit()
# Time units are in ms
bind , = seek_snap(-1000)
bind . = seek_snap(1000)
bind < = seek_snap(-5000)
bind > = seek_snap(5000)
# You can call multiple fns in sequence
bind [ = seek_snap(-5000) ; pause()
bind ] = seek_snap(5000) ; pause()

# Audio backend to use:
# values: pulseaudio, pipewire, none (auto)
# default: (auto)
audio_backend = "pipewire"

# Show milliseconds in timecodes
ui_timecode_ms = true

# So each line has form
# 1. bind {key} = fn(arg1, arg2, ...)
# 2. {opt} = {expr}
